### PR TITLE
Faster convolutions

### PR DESCRIPTION
**Pull request by Seon82**
Optimized the code for convolutions, improving the speed of `_wrapper` by about 60.

The core idea is to compute the convolutions on the whole image at once instead of doing it block by block, which helps quite a bit with the numpy overhead. I also  tried to accelerate the convolving itself by:
* determining the convolution for 4 "base kernels" ([[1,0],[0,0]], [[0,1],[0,0]], etc...)
* calculating every convolution in CONVOLUTIONS as a linear combination of these pre-computed base convolutions

### CODE REVIEW

**Comment by sedthh** [comment]
Bro I am so sorry, I just finished with the new release of Pyxelate that isn't compatible with the previous version

**Comment by Seon82** [comment]
Dang! The new version looks dope though, looking forward to using it :)

**Comment by sedthh** [comment]
Really appreciate the work you've done here though! If you have the time, maybe you can take a look at the various dithering implementations? I couldn't figure out how to implement most of them without loops so they are pretty slow.

Thanks again!

**Comment by Seon82** [comment]
Sure, I'll take a look!

**Pull request closed without merging**
